### ISSUE TITLE
Number of LSTM Time Units

### ISSUE THREAD

**Issue by ErolCitak** [IDKiro/action-recognition-pytorch#8]
Hi,

First of all, thank you for this such a great effort. But i'm not able to find the maximum frame limitation's indicator. I mean that i couldn't find the number of LSTM time units. 

For example; if i use only first 16 frames, my tensor should be like this [16,3,224,224]. So if my video larger than 16 frames, i only pick first 16 frames, otherwise i think i sould do padding before feeding to lstm.

Accordingly what should be the indicator (16 in my previous example) in here and where can i change it? 

Thanks again
Best wishes

**Comment by IDKiro** [comment]
RNN (also LSTM) does not limit the length of the input sequence.
However, according to my colleague’s experience, it seems that PyTorch has modified the LSTM api after v1.4.
If you have problems with use, you can try to lower the version of PyTorch.
If you don't understand the code, maybe you can try Debug to observe the changes of variables.
I’m very sorry, I don’t have time to review my code in detail because I’m very busy recently.
I will try to update the dataset loader after the end of the project.
